//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aplicacion_notas
    {
        public int id_app_notas { get; set; }
        public int id_ofer_crit { get; set; }
        public int id_candi_ofer { get; set; }
        public decimal notas { get; set; }
    
        public virtual candidatos_ofertas candidatos_ofertas { get; set; }
        public virtual ofertas_criterios ofertas_criterios { get; set; }
    }
}
