//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cv_exp_laboral
    {
        public int id_cv_exp_laboral { get; set; }

        [Required(ErrorMessage = "Ingrese su curriculum")]
        [Display(Name = "Curriculum")]
        public int id_curriculum { get; set; }

        [Required(ErrorMessage = "Ingrese su experiencia profesional")]
        [Display(Name = "Experiencia profesional")]
        public int id_exp_profesional { get; set; }
    
        public virtual curriculum curriculum { get; set; }
        public virtual exp_profesional exp_profesional { get; set; }
    }
}
