//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_profesional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exp_profesional()
        {
            this.cv_exp_laboral = new HashSet<cv_exp_laboral>();
        }
    
        public int id_exp_profesional { get; set; }
        public string empresa { get; set; }
        public string cargo { get; set; }
        public string jefe_inmediato { get; set; }
        public System.DateTime fech_inicio { get; set; }
        public System.DateTime fech_fin { get; set; }
        public decimal salario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cv_exp_laboral> cv_exp_laboral { get; set; }
    }
}
