//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofertas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ofertas()
        {
            this.candidatos_ofertas = new HashSet<candidatos_ofertas>();
            this.ofertas_criterios = new HashSet<ofertas_criterios>();
        }
    
        public int id_oferta { get; set; }
        public string nombre_puesto { get; set; }
        public string tipo_contrato { get; set; }
        public int numero_plazas { get; set; }
        public int id_empleado { get; set; }
        public decimal salario_oferta { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
        public System.DateTime fecha_finalizacion { get; set; }
        public string otros_detalles { get; set; }
        public string mision_puesto { get; set; }
        public string funciones_basicas { get; set; }
        public string otros_aspectos { get; set; }
        public string grado_academico { get; set; }
        public string especialidad { get; set; }
        public string nivel_experiencia { get; set; }
        public string genero { get; set; }
        public string idiomas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatos_ofertas> candidatos_ofertas { get; set; }
        public virtual empleados empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ofertas_criterios> ofertas_criterios { get; set; }
    }
}
